//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinMateAdminWebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_Logs
    {
        public int chat_id { get; set; }
        public int user_id { get; set; }
        public string log_type { get; set; }
        public string image_path { get; set; }
        public string diagnosis_result { get; set; }
        public string message { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
