// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspRestServer.Models;

public partial class ChatLog
{
    public int ChatId { get; set; }

    public int UserId { get; set; }

    public string LogType { get; set; }

    public string ImagePath { get; set; }

    public string DiagnosisResult { get; set; }

    public string Message { get; set; }

    public string Response { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual User User { get; set; }
}