// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AspRestServer.Models;

public partial class MyAppDbContext : DbContext
{
    public MyAppDbContext(DbContextOptions<MyAppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChatLog> ChatLogs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChatLog>(entity =>
        {
            entity.HasKey(e => e.ChatId).HasName("PK__chat_log__FD040B1719866FCE");

            entity.ToTable("chat_logs");

            entity.HasIndex(e => e.LogType, "IX_chat_logs_log_type");

            entity.HasIndex(e => new { e.UserId, e.Timestamp }, "IX_chat_logs_user_time").IsDescending(false, true);

            entity.Property(e => e.ChatId).HasColumnName("chat_id");
            entity.Property(e => e.DiagnosisResult).HasColumnName("diagnosis_result");
            entity.Property(e => e.ImagePath)
                .HasMaxLength(512)  
                .IsUnicode(false)
                .HasColumnName("image_path");
            entity.Property(e => e.LogType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("log_type");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.Response).HasColumnName("response");
            entity.Property(e => e.Timestamp)
                .HasPrecision(3)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("timestamp");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.ChatLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_chat_logs_users");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__users__B9BE370FE95118F7");

            entity.ToTable("users");

            entity.HasIndex(e => e.Username, "UQ__users__F3DBC572227A7293").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}